### ISSUE TITLE
[Question/Request] Stop playing on empty channel

### ISSUE THREAD

**Issue by zaitokun** [mephasor/mephaBot#2]
Hi! 
I would like to know if there is some way to stop playing on empty channel? 
+also disconnect from the channel too.

I'm a totally noob with python, but if you give me an idea I will be happy.
thanks. :)

Sorry for my bad English. xD;

**Comment by mephasor** [comment]
Hi :) 
Sorry for the late response. You can always stop playing with the !0 comand as far as I remember. 
I will look into stopping on empty stream as soon as I have a little bit of time.

**Comment by zaitokun** [comment]
Oh, nice, and don't worry, take your time.
Thanks for this awesome bot. <3
